# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    contact_mailer: AppBundle\Mailer\Mailer

services:
      app.mailer.mailer:
          class: '%contact_mailer%'
          arguments: ['@mailer', '@templating']
          calls:
              - [setContainer, ['@service_container']]